/**
 * Zod schemas for auth routes
 */

import { z } from 'zod';

/**
 * Roles a user may pick for themselves. ADMIN is assigned from ADMIN_EMAIL at
 * first sign-up; PARENT is reserved for the managed-player flow. Neither is
 * self-selectable.
 */
export const SELF_SELECTABLE_ROLES = ['PLAYER', 'COACH'] as const;
export type SelfSelectableRole = (typeof SELF_SELECTABLE_ROLES)[number];

export const updateRoleSchema = z.object({
  role: z.enum(SELF_SELECTABLE_ROLES, {
    message: "Role must be 'PLAYER' or 'COACH'",
  }),
});

export type UpdateRoleInput = z.infer<typeof updateRoleSchema>;

/**
 * OAuth `state` and PKCE parameters (audit #5). Both are generated by the
 * mobile client: `state` is echoed back by WorkOS on the redirect and checked
 * on-device against the pending sign-in; `code_challenge` is forwarded to
 * WorkOS, which then refuses to exchange the code without the matching
 * `code_verifier` (RFC 7636 S256).
 */
const STATE_PATTERN = /^[A-Za-z0-9_-]{16,256}$/;
/** RFC 7636 §4.1: 43–128 chars of [A-Za-z0-9-._~]. Our challenge is base64url, a subset. */
const PKCE_PATTERN = /^[A-Za-z0-9\-._~]{43,128}$/;

export const oauthStateSchema = z.string().regex(STATE_PATTERN, 'Invalid state');
export const pkceChallengeSchema = z.string().regex(PKCE_PATTERN, 'Invalid code_challenge');
export const pkceVerifierSchema = z.string().regex(PKCE_PATTERN, 'Invalid code_verifier');

export const loginQuerySchema = z
  .object({
    state: oauthStateSchema.optional(),
    code_challenge: pkceChallengeSchema.optional(),
  })
  .refine((q) => (q.state === undefined) === (q.code_challenge === undefined), {
    message: 'state and code_challenge must be supplied together',
  });

export const callbackQuerySchema = z
  .object({
    code: z.string().min(1, 'Authorization code is required'),
    state: oauthStateSchema.optional(),
    code_verifier: pkceVerifierSchema.optional(),
  })
  .refine((q) => (q.state === undefined) === (q.code_verifier === undefined), {
    message: 'state and code_verifier must be supplied together',
  });
